### ISSUE TITLE
The license of the repository

### ISSUE THREAD

**Issue by Hu-Yuyang** [chenkang455/TRMD#2]
I am very impressed with the work you have done!

I am interested in further exploring your work, but I couldn't find information regarding the license information. Could you please let me know which license applies to this repository?

Thanks!

**Comment by chenkang455** [comment]
Hello, thank you for your interest and kind words about our project! Regarding the license question, this project is licensed under the MIT License.

**Comment by Hu-Yuyang** [comment]
Thank you so much! Once again, I really appreciate your outstanding work.

**Comment by Hu-Yuyang** [comment]
The license is MIT License.
